// Code generated by sqlc. DO NOT EDIT.
// source: contribution.sql

package db

import (
	"context"
	"database/sql"
)

const createContribution = `-- name: CreateContribution :one
INSERT INTO contributions (
  "voteBalance", "pullRequest", type, "privateKey", merged, "storyId", balance
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, pullRequest, type, merged, balance, voteBalance, privateKey, storyId, createdAt
`

type CreateContributionParams struct {
	VoteBalance sql.NullInt32
	PullRequest string
	Type        string
	PrivateKey  string
	Merged      sql.NullBool
	StoryId     int32
	Balance     sql.NullInt32
}

func (q *Queries) CreateContribution(ctx context.Context, arg CreateContributionParams) (Contribution, error) {
	row := q.db.QueryRowContext(ctx, createContribution,
		arg.VoteBalance,
		arg.PullRequest,
		arg.Type,
		arg.PrivateKey,
		arg.Merged,
		arg.StoryId,
		arg.Balance,
	)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.PullRequest,
		&i.Type,
		&i.Merged,
		&i.Balance,
		&i.VoteBalance,
		&i.PrivateKey,
		&i.StoryId,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContribution = `-- name: DeleteContribution :exec
DELETE FROM contributions
`

func (q *Queries) DeleteContribution(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteContribution)
	return err
}

const getContribution = `-- name: GetContribution :one
SELECT id, pullRequest, type, merged, balance, voteBalance, privateKey, storyId, createdAt FROM contributions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetContribution(ctx context.Context, id int32) (Contribution, error) {
	row := q.db.QueryRowContext(ctx, getContribution, id)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.PullRequest,
		&i.Type,
		&i.Merged,
		&i.Balance,
		&i.VoteBalance,
		&i.PrivateKey,
		&i.StoryId,
		&i.CreatedAt,
	)
	return i, err
}

const listContributions = `-- name: ListContributions :many
SELECT id, pullRequest, type, merged, balance, voteBalance, privateKey, storyId, createdAt FROM contributions
ORDER BY id
`

func (q *Queries) ListContributions(ctx context.Context) ([]Contribution, error) {
	rows, err := q.db.QueryContext(ctx, listContributions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contribution
	for rows.Next() {
		var i Contribution
		if err := rows.Scan(
			&i.ID,
			&i.PullRequest,
			&i.Type,
			&i.Merged,
			&i.Balance,
			&i.VoteBalance,
			&i.PrivateKey,
			&i.StoryId,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContribution = `-- name: UpdateContribution :exec
UPDATE contributions 
SET "voteBalance"= $2, "pullRequest"= $3, type= $4, "privateKey"= $5, merged= $6, "storyId"= $7, balance= $8
WHERE id = $1
`

type UpdateContributionParams struct {
	ID          int32
	VoteBalance sql.NullInt32
	PullRequest string
	Type        string
	PrivateKey  string
	Merged      sql.NullBool
	StoryId     int32
	Balance     sql.NullInt32
}

func (q *Queries) UpdateContribution(ctx context.Context, arg UpdateContributionParams) error {
	_, err := q.db.ExecContext(ctx, updateContribution,
		arg.ID,
		arg.VoteBalance,
		arg.PullRequest,
		arg.Type,
		arg.PrivateKey,
		arg.Merged,
		arg.StoryId,
		arg.Balance,
	)
	return err
}
