// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Company struct {
	ID        int32
	Name      string
	Github    string
	Createdat time.Time
}

type Contribution struct {
	ID          int32
	Pullrequest string
	Value       sql.NullInt32
	Type        string
	Key         string
	Merged      sql.NullBool
	Companyid   int32
	Createdat   time.Time
}

type User struct {
	ID        int32
	Name      string
	Key       string
	Job       string
	Createdat time.Time
}

type Usercompany struct {
	ID        int32
	Companyid int32
	Userid    int32
}

type Usercontribution struct {
	ID             int32
	Companyid      int32
	Contributionid int32
}
