// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Company struct {
	ID         int32
	Name       string
	Github     string
	PrivateKey string
	Balance    sql.NullInt32
	CreatedAt  time.Time
}

type Contribution struct {
	ID          int32
	PullRequest string
	Type        string
	Merged      sql.NullBool
	Balance     sql.NullInt32
	VoteBalance sql.NullInt32
	StoryId     int32
	CreatedAt   time.Time
}

type Story struct {
	ID          int32
	PullRequest string
	Type        string
	Merged      sql.NullBool
	Balance     sql.NullInt32
	VoteBalance sql.NullInt32
	CompanyId   int32
	CreatedAt   time.Time
}

type User struct {
	ID        int32
	Name      string
	PublicKey string
	Job       string
	CreatedAt time.Time
}

type Usercompany struct {
	ID        int32
	CompanyId int32
	UserId    int32
}

type Usercontribution struct {
	ID             int32
	CompanyId      int32
	ContributionId int32
	Balance        sql.NullInt32
	VoteBalance    sql.NullInt32
}
