// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Company struct {
	ID        int32
	Name      string
	Github    string
	CreatedAt time.Time
}

type Contribution struct {
	ID          int32
	PullRequest string
	Value       sql.NullInt32
	Type        string
	Key         string
	Merged      sql.NullBool
	CompanyId   int32
	CreatedAt   time.Time
}

type User struct {
	ID        int32
	Name      string
	Key       string
	Job       string
	CreatedAt time.Time
}

type Usercompany struct {
	ID        int32
	CompanyId int32
	UserId    int32
}

type Usercontribution struct {
	ID             int32
	CompanyId      int32
	ContributionId int32
}
